### ISSUE TITLE
XmasLightControllerForVixenSSRs will not compile 

### ISSUE THREAD

**Issue by Simontho001** [spaelectronics/8CH-AC-Dimmer#1]
when i try to upload the code to my arduino mega 2560 i get the error

> exit status 1
'power_usart3_disable' was not declared in this scope 
how do i fix this will i need a library be cause i did install a library called avr/power.h but are there other ones that i need?

**Comment by spaelectronics** [comment]
Try using a older version of Arduino IDE. 
I can't remember which version I used to test, or else I would tell you which version to use.

**Comment by Simontho001** [comment]
That seamed to fix it. Looked at some other threads about the error code it gave and said that you should use 1.6.9 so that seams go be the one that works best

**Comment by spaelectronics** [comment]
That's good! Thanks for the update!
